# Numpy learning

In [39]:
import numpy as np

## Rank of an array
Number of dimensions of the array is called rank of the array

In [40]:
rank1Array = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) #Rank 1 array
print(rank1Array, 'Shape = ',rank1Array.shape, 'Type = ', rank1Array.dtype)
print('Class Name : ' + rank1Array.__class__.__name__)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] Shape =  (16,) Type =  int32
Class Name : ndarray


In [73]:
rank2Array_1 = np.array([[1,2,3,4,5]]) #Rank 2 array
rank2Array_2 = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19]]) #Rank 2
print(rank2Array_1, 'Shape = ',rank2Array_1.shape)
print(rank2Array_2, 'Shape = ',rank2Array_2.shape)

[[1 2 3 4 5]] Shape =  (1, 5)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] Shape =  (4, 5)


## ndarray functions

In [74]:
print('Shape : ', rank2Array_2.shape)
print('Dimensions : ', rank2Array_2.ndim)
print('Number of elements : ', rank2Array_2.size)
print('Type : ', rank2Array_2.dtype)

print('1D iterator : ', rank2Array_2.flat)
print('1D array form : ', rank2Array_2.flatten())

print('Transpose :\n ', rank2Array_2.T)

Shape :  (4, 5)
Dimensions :  2
Number of elements :  20
Type :  int32
1D iterator :  <numpy.flatiter object at 0x000002EAD1BACCB0>
1D array form :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Transpose :
  [[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [75]:
print('Reshaped : \n', rank2Array_2.reshape((20,1)))
print('Resize :', rank2Array_2.resize((5,7))) #Resize directly changes the array
print(rank2Array_2)

print('Memory layout information : ', rank2Array_2.flags)

Reshaped : 
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]]
Resize : None
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]]
Memory layout information :    C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


## Rank 1 array indexing

In [5]:
print(rank1Array[0])
print(rank1Array[1])
print(rank1Array[-1])
print(rank1Array[1:3]) #start : end # [start : end)
print(rank1Array[1:-1])
print(rank1Array[::2]) # start : end : step
print(rank1Array[2:11:2])
print(rank1Array[::-1]) # reverse an array
print(rank1Array[11:4:-1])

0
1
15
[1 2]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  2  4  6  8 10 12 14]
[ 2  4  6  8 10]
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[11 10  9  8  7  6  5]


## Rank 2 array indexing

In [6]:
print(rank2Array_2[2,4]) # [row,col]
print(rank2Array_2[2,])
print(rank2Array_2[:5:2,:5:2]) # [row start : end , col start : end]
print(rank2Array_2[:,::-1]) # Reverse each row
print(rank2Array_2[::-1,:]) # Reverse the order of rows 

14
[10 11 12 13 14]
[[ 0  2  4]
 [10 12 14]]
[[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [14 13 12 11 10]
 [19 18 17 16 15]]
[[15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


### inf and NaN

In [62]:
print(np.inf)
print(np.nan)

inf
nan


## Matrix operations

In [54]:
MatX = np.array([[2,3,4],[5,8,9],[1,2,2]])
MatY = np.array([[1,2],[5,9],[9,9]])
MatI = np.identity(3)

#Dot product
print(MatX.dot(MatY))
print(MatX.dot(MatI))

#element wise operations
print(MatX * MatI)
print(MatX / MatI)
print(MatX + MatI + MatI)


[[ 53  67]
 [126 163]
 [ 29  38]]
[[2. 3. 4.]
 [5. 8. 9.]
 [1. 2. 2.]]
[[2. 0. 0.]
 [0. 8. 0.]
 [0. 0. 2.]]
[[ 2. inf inf]
 [inf  8. inf]
 [inf inf  2.]]
[[ 4.  3.  4.]
 [ 5. 10.  9.]
 [ 1.  2.  4.]]


C:\Users\gsgur\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: RuntimeWarning: divide by zero encountered in true_divide
  # This is added back by InteractiveShellApp.init_path()


# Numpy functions

### arange

In [ ]:
print(np.arange(5))
print(np.arange(3,10)) # (start, end)
print(np.arange(3,30,5))  # (start, end, step)
print(np.arange(25).reshape((5,5)))

### eye and identity

In [8]:
print(np.eye(5, dtype=np.float))
print(np.identity(5, dtype=np.float))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Ones and Zeros

In [47]:
print(np.ones(5))
print(np.ones((5,3)))
print(np.zeros(4))
print(np.zeros((4,2)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


### Any and All

In [61]:
XX = [[1,2,3],[4,5,6],[7,8,0],[1,2,3],[4,5,6]]
YY = [[0,2],[0,4]]

print('Axis = None')
print(np.any(XX))
print(np.all(XX))
print(np.any(YY))
print(np.all(YY))

print('Axis = 0')
print(np.any(XX, axis = 0))
print(np.all(XX, axis = 0))
print(np.any(YY, axis = 0))
print(np.all(YY, axis = 0))

print('Axis = 1')
print(np.any(XX, axis = 1))
print(np.all(XX, axis = 1))
print(np.any(YY, axis = 1))
print(np.all(YY, axis = 1))

Axis = None
True
False
True
False
Axis = 0
[ True  True  True]
[ True  True False]
[False  True]
[False  True]
Axis = 1
[ True  True  True  True  True]
[ True  True False  True  True]
[ True  True]
[False False]


### Repeat

In [79]:
newMatX = np.array([[2,3,4],[0,11,1],[2,2,6]])
print(np.repeat(newMatX, 3, axis=0))
print(np.repeat(newMatX, 3, axis=1))

[[ 2  3  4]
 [ 2  3  4]
 [ 2  3  4]
 [ 0 11  1]
 [ 0 11  1]
 [ 0 11  1]
 [ 2  2  6]
 [ 2  2  6]
 [ 2  2  6]]
[[ 2  2  2  3  3  3  4  4  4]
 [ 0  0  0 11 11 11  1  1  1]
 [ 2  2  2  2  2  2  6  6  6]]


### Concatination

In [83]:
newMatX = np.array([[2,3,4],[0,11,1],[2,2,6]])
newMatY = np.array([[1,1,1],[2,2,2],[3,3,3]])

print(np.concatenate((newMatX,newMatY), axis=0))
print(np.concatenate((newMatX,newMatY), axis=1))

[[ 2  3  4]
 [ 0 11  1]
 [ 2  2  6]
 [ 1  1  1]
 [ 2  2  2]
 [ 3  3  3]]
[[ 2  3  4  1  1  1]
 [ 0 11  1  2  2  2]
 [ 2  2  6  3  3  3]]
