# PyTorch Learning
# =============== (Guru Sarath Thangamani - 21st Oct 2020)

In [2]:
import torch 
import numpy as np

## Creating Tensors

In [24]:
TensorX = torch.empty(2, 3)
print(TensorX)

TensorX = torch.rand(5, 3, dtype=torch.double)
print(TensorX)

TensorX = torch.randn(3, 3, dtype=torch.double)
print(TensorX)

TensorX = torch.zeros(5)
print(TensorX)

TensorX = torch.ones(5,2,3)
print(TensorX)

tensor([[0., 0., 0.],
        [0., 0., 6.]])
tensor([[0.5772, 0.2165, 0.1945],
        [0.6190, 0.8294, 0.2244],
        [0.5861, 0.2548, 0.7942],
        [0.4051, 0.7229, 0.9242],
        [0.3353, 0.8668, 0.2588]], dtype=torch.float64)
tensor([[-0.8249, -1.3473, -0.4149],
        [ 0.5419,  1.0035,  0.4220],
        [ 1.0188, -0.3198, -0.0666]], dtype=torch.float64)
tensor([0., 0., 0., 0., 0.])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])


In [18]:
# Creating tensors from data

TensorX = torch.tensor([1,2,3])
print(TensorX)

TensorX = torch.tensor( [[1,2,3], [4,5,6]] , dtype=torch.float)  # Forcing a datatype
print(TensorX)

TensorX = torch.tensor( [[1.4,2.6,3.6], [4.4,5.3,6.1]] , dtype=torch.int)  # Forcing a datatype
print(TensorX)

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [16]:
# Get the size of tensor
print(TensorX.size())

torch.Size([2, 3])


## Operations

In [23]:
x = torch.tensor( [ [1,2,3] , [6,8,8] ] )
y = torch.tensor( [ [4,1,4] , [1,1,2] ] )

z = x + y
print(z)
print(x)
print('==========================')

z = torch.add(x,y)
print(z)
print(x)
print('==========================')

z = x.add_(y) # x = x + y # Result is also stored in x 
print(z)
print(x) 
print('==========================')


tensor([[ 5,  3,  7],
        [ 7,  9, 10]])
tensor([[1, 2, 3],
        [6, 8, 8]])
tensor([[ 5,  3,  7],
        [ 7,  9, 10]])
tensor([[1, 2, 3],
        [6, 8, 8]])
tensor([[ 5,  3,  7],
        [ 7,  9, 10]])
tensor([[ 5,  3,  7],
        [ 7,  9, 10]])


#### Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

## Indexing (numpy style indexing) and Reshaping (view)

In [27]:
x = torch.tensor( [ [1,2,3] , [4,5,6] , [7,8,9] ] )

# You can do numpy style indexing in pytorch
print(x[:,1])
print(x[:,[0,1]])
print(x[[0,2],[0,1]])

tensor([2, 5, 8])
tensor([[1, 2],
        [4, 5],
        [7, 8]])
tensor([1, 8])


In [35]:
x.view(9) # View DOES NOT modify the tensor in-place

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
x.view(3,3,1) # Channel x Row x Col

tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])

In [37]:
x.view(1,3,3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

# Numpy integration

In [39]:
x = torch.randn(4,4)
print(x)
print(x.numpy())

tensor([[ 0.3196,  0.5136, -3.2624, -1.2054],
        [-0.5133,  1.1400, -2.3886, -1.0646],
        [-0.1924, -2.0602, -0.0669, -0.2594],
        [-0.9280, -1.4014,  1.5821, -0.6943]])


array([[ 0.31960917,  0.5135996 , -3.262378  , -1.2054011 ],
       [-0.51329434,  1.1399745 , -2.3885808 , -1.0646492 ],
       [-0.1924316 , -2.0601523 , -0.06690224, -0.25944534],
       [-0.92797995, -1.4014028 ,  1.5821017 , -0.6943422 ]],
      dtype=float32)

In [49]:
x = np.arange(5,15)
print(x)

y = torch.tensor(x)   # Creates a New Tensor form numpy array
x[0] = 999  # Changing x does not change y
print(y)
x[0] = 5

print('==================================')

y = torch.from_numpy(x)    # Creates a Tensor using the existing numpy array
x[0] = 999                 # In this case changing the numpy array alo changes the tensor
print(y)

[ 5  6  7  8  9 10 11 12 13 14]
tensor([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14], dtype=torch.int32)
tensor([999,   6,   7,   8,   9,  10,  11,  12,  13,  14], dtype=torch.int32)


## CUDA

In [51]:
if torch.cuda.is_available():
    print('CUDA is available')

CUDA is available


In [55]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device) #
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]], device='cuda:0')
tensor([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.]], dtype=torch.float64)


## Autograd: Automatic Differentiation

In [68]:
x = torch.tensor([7,8,9], requires_grad=True, dtype=torch.double)
y = x*x
y = torch.sum(y)
print(y)

tensor(194., dtype=torch.float64, grad_fn=<SumBackward0>)


In [69]:
y.backward()
x.grad

tensor([14., 16., 18.], dtype=torch.float64)

## Linear Regression

In [76]:
DataSet = np.genfromtxt('LR_DataSet_Toy.csv', delimiter = ',', skip_header=1)
DataSet.shape

(3432, 6)

In [77]:
y = DataSet[:,-1]
X = DataSet[:,0:-1]

print(y.shape)
print(X.shape)

(3432,)
(3432, 5)


In [96]:
num_train_samples = 3000

X_train = X[0:num_train_samples, :]
X_val = X[num_train_samples:, :]

y_train = y[0:num_train_samples]
y_val = y[num_train_samples:]

print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)

X_train_tensor = torch.from_numpy(X_train)
y_train_tensor = torch.from_numpy(y_train).view(-1,1)

X_val_tensor = torch.from_numpy(X_val)
y_val_tensor = torch.from_numpy(y_val).view(-1,1)

(3000, 5) (3000,)
(432, 5) (432,)


In [97]:
num_input_features = X_train.shape[1]
num_output_features = 1

LR = torch.nn.Linear(num_input_features, num_output_features)
print(LR.weight)
print(LR.bias)

Parameter containing:
tensor([[ 0.1432,  0.1108,  0.2393,  0.4025, -0.3647]], requires_grad=True)
Parameter containing:
tensor([0.0481], requires_grad=True)


In [98]:
list(LR.parameters())

[Parameter containing:
 tensor([[ 0.1432,  0.1108,  0.2393,  0.4025, -0.3647]], requires_grad=True),
 Parameter containing:
 tensor([0.0481], requires_grad=True)]

In [99]:
preds = LR(X_train_tensor.float())
print(preds)

tensor([[0.7206],
        [0.5993],
        [1.2819],
        ...,
        [1.0416],
        [1.3298],
        [1.1346]], grad_fn=<AddmmBackward>)


### Loss function

In [100]:
import torch.nn.functional as F

In [101]:
loss_fn = F.mse_loss
loss = loss_fn(LR(X_train_tensor.float()), y_train_tensor)
print(loss)

tensor(877.8418, dtype=torch.float64, grad_fn=<MseLossBackward>)


### Optimizer

In [110]:
opt = torch.optim.SGD(LR.parameters(), lr=1e-5)

### Training

In [111]:
if torch.cuda.is_available():  
    dev = "cuda:0" 
else:  
    dev = "cpu"

device = torch.device(dev)

In [121]:
epochs = 100000

for i in range(epochs):
    pred = LR(X_train_tensor.float())

    # 2. Calculate loss
    loss = loss_fn(pred.float(), y_train_tensor.float())

    # 3. Compute gradients
    loss.backward()

    # 4. Update parameters using gradients
    opt.step()

    # 5. Reset the gradients to zero
    opt.zero_grad()
    
    if i % 10 == 0:
        print('Loss = ', loss)

Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)
Loss =  tensor(0.7683, grad_fn=<MseLossBackward>)


KeyboardInterrupt: 

In [120]:
print(LR.weight)
print(LR.bias)

Parameter containing:
tensor([[0.9279, 1.1546, 2.9884, 8.9811, 2.0066]], requires_grad=True)
Parameter containing:
tensor([3.7331], requires_grad=True)


In [ ]:
# Actual parameters used in the toy dataset
# y = x1 + x2 + 3*x3 + 9*x4 + 2*x5 + 3